name = "nbdevlab"
main = "dist/worker.js"
compatibility_date = "2024-10-01"

# Default build = safe preview, no custom routes
workers_dev = true
routes = []  # nothing bound
preview_urls = true

[env.production]
workers_dev = false
routes = ["https://www.nbdevlab.com/*", "https://nbdevlab.com/*"]

[env.preview]
workers_dev = true
routes = []  # no domains
