local_backend: false

backend:
  name: github
  repo: 0xC0FFEEBEEF/nbdevlab
  branch: main
  base_url: https://www.nbdevlab.com


  auth_endpoint: api/auth
  site_domain: www.nbdevlab.com

media_folder: "public/src/assets/uploads"
public_folder: "/src/assets/uploads"

collections:
  - name: "projects"
    label: "Projects"
    label_singular: "Project"
    folder: "src/content/projects"
    create: true
    slug: "{{slug}}"
    preview_path: "projects/{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "slug", label: "Slug", widget: "string" }
      - { name: "date", label: "Date", widget: "datetime", format: "YYYY-MM-DD" }
      - name: "status"
        label: "Status"
        widget: "select"
        options:
          - { label: "Shipped", value: "shipped" }
          - { label: "Building", value: "building" }
          - { label: "Research", value: "research" }
      - { name: "tags", label: "Tags", widget: "list" }
      - { name: "problem", label: "Problem Summary", widget: "text" }
      - { name: "constraints", label: "Constraints", widget: "list" }
      - { name: "stack", label: "Stack", widget: "list" }
      - { name: "lessons", label: "Lessons", widget: "list" }
      - name: "links"
        label: "Links"
        widget: "object"
        required: false
        fields:
          - { name: "repo", label: "Repository URL", widget: "string", required: false }
          - { name: "demo", label: "Demo URL", widget: "string", required: false }
      - { name: "body", label: "Case Study", widget: "markdown" }
  - name: "homepage"
    label: "Homepage"
    files:
      - name: "dashboard"
        label: "Hero & Highlights"
        file: "src/content/homepage/dashboard.yaml"
        format: "yaml"
        fields:
          - label: "Highlight Cards"
            name: "highlightCards"
            widget: "list"
            summary: "{{fields.title}}"
            fields:
              - { name: "title", label: "Title", widget: "string" }
              - { name: "description", label: "Description", widget: "text" }
              - { name: "href", label: "Link", widget: "string" }
              - { name: "badge", label: "Badge", widget: "string" }
              - { name: "accent", label: "Accent (RGB)", widget: "string", required: false }
          - label: "GitHub Activity Card"
            name: "activityCard"
            widget: "object"
            fields:
              - { name: "title", label: "Title", widget: "string" }
              - { name: "description", label: "Description", widget: "text" }
              - { name: "href", label: "Link", widget: "string" }
              - { name: "badge", label: "Badge", widget: "string" }
              - { name: "accent", label: "Accent (RGB)", widget: "string", required: false }
              - { name: "repo", label: "Repository", widget: "string" }
              - { name: "timestamp", label: "Timestamp", widget: "string" }
              - { name: "meta", label: "Meta", widget: "string", required: false }
          - label: "Now Items"
            name: "nowItems"
            widget: "list"
            fields:
              - { name: "label", label: "Label", widget: "string" }
              - { name: "detail", label: "Detail", widget: "text" }
          - label: "Timeline"
            name: "timeline"
            widget: "list"
            fields:
              - { name: "date", label: "Date", widget: "string" }
              - { name: "title", label: "Title", widget: "string" }
              - { name: "detail", label: "Detail", widget: "text" }
