local_backend: false

backend:
  name: github
  repo: 0xC0FFEEBEEF/nbdevlab        
  branch: main
  base_url: https://www.nbdevlab.com

  
  auth_endpoint: api/auth
  site_domain: www.nbdevlab.com

media_folder: "public/src/assets/uploads"       # files committed here
public_folder: "/src/assets/uploads"         # how they’re referenced in pages

collections:
  - name: "projects"
    label: "Projects"
    label_singular: "Project"
    folder: "src/content/projects"
    create: true
    slug: "{{slug}}"
    preview_path: "projects/"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "text", required: false }
      - { name: "link", label: "Link (optional)", widget: "string", required: false }
      - { name: "tags", label: "Tags", widget: "list", required: false }
      - { name: "image", label: "Image (optional)", widget: "image", required: false }   # ← not required
      - { name: "featured", label: "Featured", widget: "boolean", required: false, default: false }
      - { name: "weight", label: "Weight (sort higher first)", widget: "number", required: false, value_type: "int", default: 0 }
      - { name: "pubDate", label: "Published", widget: "datetime", required: false }
      - { name: "draft", label: "Draft", widget: "boolean", required: false, default: false }
      - { name: "body", label: "Body", widget: "markdown", required: false }
