name: Deploy Cloudflare Worker

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy preview (workers.dev)
        if: ${{ github.event_name == 'pull_request' }}
        run: npx wrangler versions upload --env preview --assets=./dist
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}

      - name: Comment preview URL
        if: ${{ github.event_name == 'pull_request' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            ✅ Preview deployed: https://nbdevlab.workers.dev
            (This uses the shared Worker in the "preview" env.)

      - name: Deploy prod version
        if: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/main' }}
        run: |
          npx wrangler versions deploy
          npx wrangler triggers deploy
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
